import { useEffect, useRef, useState } from "react";

const MODEL_URL = "https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite";
const WASM_URL = "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm";

export default function BrowserFaceDemo() {
  const videoRef = useRef(null); const canvasRef = useRef(null); const detectorRef = useRef(null); const streamRef = useRef(null); const frameRef = useRef(null); const lastFacesRef = useRef(0); const [status, setStatus] = useState("ready"); const [error, setError] = useState(""); const [metrics, setMetrics] = useState({ fps: "0.0", faces: 0, tracks: 0, confidence: "-" }); const [feed, setFeed] = useState(["waiting for camera permission"]);
  useEffect(() => () => { if (frameRef.current) cancelAnimationFrame(frameRef.current); if (streamRef.current) streamRef.current.getTracks().forEach((track) => track.stop()); }, []);
  async function loadDetector() { if (detectorRef.current) return detectorRef.current; const vision = await import("@mediapipe/tasks-vision"); const fileset = await vision.FilesetResolver.forVisionTasks(WASM_URL); detectorRef.current = await vision.FaceDetector.createFromOptions(fileset, { baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" }, runningMode: "VIDEO", minDetectionConfidence: 0.45 }); return detectorRef.current; }
  function pushFeed(message) { setFeed((items) => [`${new Date().toLocaleTimeString("en-GB")} - ${message}`, ...items].slice(0, 8)); }
  async function start() { setError(""); setStatus("requesting"); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 960, height: 540 }, audio: false }); streamRef.current = stream; videoRef.current.srcObject = stream; await videoRef.current.play(); pushFeed("CAMERA PERMISSION GRANTED"); setStatus("loading"); await loadDetector(); setStatus("running"); pushFeed("BROWSER FACE DETECTOR READY"); loop(); } catch (err) { setStatus("error"); setError(err?.message || "Camera or browser model unavailable."); pushFeed("DEMO UNAVAILABLE"); } }
  function loop() { const video = videoRef.current; const canvas = canvasRef.current; const ctx = canvas.getContext("2d"); let last = performance.now(); let smoothFps = 0; const render = () => { if (!video || video.readyState < 2 || !detectorRef.current) return; const now = performance.now(); const delta = Math.max(1, now - last); last = now; smoothFps = smoothFps * .9 + (1000 / delta) * .1; canvas.width = video.videoWidth || 960; canvas.height = video.videoHeight || 540; ctx.clearRect(0, 0, canvas.width, canvas.height); const result = detectorRef.current.detectForVideo(video, now); const detections = result.detections || []; detections.forEach((face, index) => { const box = face.boundingBox; const x = box.originX; const y = box.originY; const w = box.width; const h = box.height; ctx.strokeStyle = "#65d8ff"; ctx.lineWidth = 3; ctx.shadowColor = "#65d8ff"; ctx.shadowBlur = 14; ctx.strokeRect(x, y, w, h); ctx.shadowBlur = 0; ctx.fillStyle = "rgba(4,12,22,.86)"; ctx.fillRect(x, Math.max(0, y - 28), 190, 24); ctx.fillStyle = "#65d8ff"; ctx.font = "14px Space Mono, monospace"; ctx.fillText(`FACE_${index + 1} / TEMPORARY`, x + 8, Math.max(17, y - 11)); }); if (detections.length !== lastFacesRef.current) { pushFeed(detections.length ? `${detections.length} FACE${detections.length === 1 ? "" : "S"} DETECTED` : "FACE LEFT FRAME"); lastFacesRef.current = detections.length; } const confidence = detections.length ? Math.round(Math.max(...detections.map((face) => face.categories?.[0]?.score || 0)) * 100) : 0; setMetrics({ fps: smoothFps.toFixed(1), faces: detections.length, tracks: detections.length, confidence: detections.length ? `${confidence}%` : "-" }); frameRef.current = requestAnimationFrame(render); }; frameRef.current = requestAnimationFrame(render); }
  return <div className="browser-face-demo"><div className="browser-demo-stage"><video ref={videoRef} autoPlay muted playsInline></video><canvas ref={canvasRef}></canvas><div className="video-overlay"><div className="hud-corner tl"></div><div className="hud-corner tr"></div><div className="hud-corner bl"></div><div className="hud-corner br"></div><div className="hud-top"><span>BROWSER / LOCAL</span><span className="rec"><span className="dot"></span>{status.toUpperCase()}</span></div></div>{status === "ready" && <div className="demo-prompt"><span className="kicker">Browser Face Detection Demo</span><h3>See the visual input layer.</h3><p>Allow camera access to detect visible faces locally in your browser. Nothing is uploaded or stored.</p><button type="button" className="btn btn-primary" onClick={start}>Start face detection</button></div>}{status === "loading" && <div className="demo-prompt"><span className="kicker">Loading model</span><h3>Preparing local detection.</h3><p>The lightweight browser model is loading. The complete OptiVox recognition engine remains a separate local application.</p></div>}</div><div className="browser-demo-side"><div className="panel"><h4 className="demo-panel-title">Camera telemetry</h4>{[["Status", status], ["Processing FPS", metrics.fps], ["Faces detected", metrics.faces], ["Temporary tracks", metrics.tracks], ["Confidence", metrics.confidence], ["Processing", "Browser local"]].map(([label, value]) => <div className="metric-row" key={label}><span>{label}</span><span className="v">{value}</span></div>)}</div><div className="panel"><h4 className="demo-panel-title">Detection feed</h4><div className="det-feed">{feed.map((item) => <div className="line" key={item}>{item}</div>)}</div></div>{error && <p className="demo-error">{error}</p>}<div className="demo-privacy"><span className="status-dot" style={{ background: "var(--ok)" }}></span><span><strong>Privacy state</strong><small>Camera frames are processed in this browser session only.</small></span></div></div></div>;
}
