export const people = [
  {
    id: 1,
    name: "Matthew",
    role: "Student",
    className: "Class A",
    status: "Present",
    confidence: 0.91,
    clockIn: "08:42",
    clockOut: null,
    method: "Automatic",
    lastSeen: "Now",
    samples: 8,
    active: true,
  },
  {
    id: 2,
    name: "Charles",
    role: "Operator",
    className: "Demo Team",
    status: "Present",
    confidence: 0.88,
    clockIn: "08:51",
    clockOut: null,
    method: "Automatic",
    lastSeen: "2 min ago",
    samples: 10,
    active: true,
  },
  {
    id: 3,
    name: "Bu Aida",
    role: "Teacher",
    className: "Class A",
    status: "Late",
    confidence: 0.84,
    clockIn: "09:21",
    clockOut: null,
    method: "Automatic",
    lastSeen: "12 min ago",
    samples: 6,
    active: true,
  },
  {
    id: 4,
    name: "Nabiil",
    role: "Student",
    className: "Class A",
    status: "Left",
    confidence: 0.89,
    clockIn: "08:39",
    clockOut: "11:52",
    method: "Manual",
    lastSeen: "1 hour ago",
    samples: 7,
    active: true,
  },
  {
    id: 5,
    name: "Pak Dani",
    role: "Staff",
    className: "Operations",
    status: "Not Yet Detected",
    confidence: null,
    clockIn: null,
    clockOut: null,
    method: "-",
    lastSeen: "Yesterday",
    samples: 5,
    active: true,
  },
];

export const visiblePeople = [
  {
    id: "p-1",
    label: "Matthew",
    type: "registered",
    confidence: 0.91,
    attendance: "Clocked in",
    visibleFor: "4m 12s",
    note: "Registered attendance",
  },
  {
    id: "p-2",
    label: "Stranger 2",
    type: "unknown",
    confidence: 0.66,
    attendance: "Presence only",
    visibleFor: "18s",
    note: "Unregistered person",
  },
  {
    id: "p-3",
    label: "Possible Spoof",
    type: "spoof",
    confidence: 0.42,
    attendance: "Blocked",
    visibleFor: "6s",
    note: "Verification required",
  },
];

export const objects = [
  { name: "Person", count: 3, confidence: 0.94, category: "identity" },
  { name: "Backpack", count: 1, confidence: 0.81, category: "accessory" },
  { name: "Cell phone", count: 1, confidence: 0.78, category: "object" },
  { name: "Book", count: 2, confidence: 0.74, category: "object" },
];

export const events = [
  {
    id: 101,
    time: "09:41:18",
    type: "ATTENDANCE_CLOCKIN",
    group: "Identity",
    severity: "Normal",
    person: "Matthew",
    location: "Class",
    confidence: 1,
    details: "Confirmed repeated recognition and clocked in automatically.",
    reviewed: true,
  },
  {
    id: 102,
    time: "09:42:04",
    type: "UNKNOWN_PERSON",
    group: "Identity",
    severity: "Attention",
    person: "Stranger 2",
    location: "Class",
    confidence: 0.66,
    details: "Unregistered face visible. Attendance not recorded.",
    reviewed: false,
  },
  {
    id: 103,
    time: "09:42:27",
    type: "OBJECT_DETECTED",
    group: "Object",
    severity: "Normal",
    person: "System",
    location: "Class",
    confidence: 0.81,
    details: "Backpack detected near tracked person.",
    reviewed: true,
  },
  {
    id: 104,
    time: "09:43:02",
    type: "SPOOF_DETECTED",
    group: "Identity",
    severity: "Warning",
    person: "Possible Spoof",
    location: "Class",
    confidence: 0.9,
    details: "Repeated anti-spoof suspicion. Attendance blocked.",
    reviewed: false,
  },
  {
    id: 105,
    time: "09:44:10",
    type: "FALL_DETECTED",
    group: "Safety",
    severity: "Critical",
    person: "Person",
    location: "Class",
    confidence: 0.85,
    details: "Pose analysis suggests possible fall.",
    reviewed: false,
  },
];

export const analytics = {
  attendanceByDay: [
    { day: "Mon", present: 18, late: 2 },
    { day: "Tue", present: 21, late: 1 },
    { day: "Wed", present: 19, late: 3 },
    { day: "Thu", present: 22, late: 2 },
    { day: "Fri", present: 20, late: 0 },
    { day: "Sat", present: 9, late: 1 },
    { day: "Today", present: 4, late: 1 },
  ],
  eventsByHour: [
    { hour: "08", events: 4 },
    { hour: "09", events: 12 },
    { hour: "10", events: 7 },
    { hour: "11", events: 5 },
    { hour: "12", events: 2 },
  ],
  securityCategories: [
    { name: "Identity", value: 8 },
    { name: "Safety", value: 3 },
    { name: "Object", value: 5 },
    { name: "System", value: 1 },
  ],
};

export function getDemoState() {
  const now = new Date();
  return {
    generatedAt: now.toISOString(),
    localTime: now.toLocaleTimeString("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    }),
    engine: {
      status: "Operational",
      camera: "Connected",
      location: "Class",
      fps: 23.8,
      uptime: "1h 14m",
      mode: "Local AI Processing",
      frameAge: "0.3s",
    },
    summary: {
      presentToday: 4,
      visibleNow: visiblePeople.length,
      unknownToday: 3,
      securityEvents: 2,
      alertsSent: 1,
      registeredPeople: people.length,
    },
    visiblePeople,
    objects,
    people,
    attendance: people,
    events,
    analytics,
  };
}
